apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: us.icr.io/azin-dev/accounts:1
          env:
          - name: DATABASE_HOST
            value: postgresql
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-name
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-password
      imagePullSecrets:
        - name: ibm-registry-secret
