apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  type: NodePort
  selector:
    app: accounts
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
